### ISSUE TITLE
烟感产品模型无法下载

### ISSUE THREAD

**Issue by ShashaZhangUSTB** [huaweicloud/huaweicloud-iot-device-sdk-python#3]
https://github.com/huaweicloud/huaweicloud-iot-device-sdk-python/blob/main/README_CN.md

**Comment by Aimini** [comment]
感谢反馈，模型可以从此处下载 [https://iot-developer.obs.cn-north-4.myhuaweicloud.com/smokeDetector.zip](https://iot-developer.obs.cn-north-4.myhuaweicloud.com/smokeDetector.zip), readme之后会由专人修复。
